### ISSUE TITLE
数据源新增页面增加预置网站

### ISSUE THREAD

**Issue by SanaeMio** [xiaoyi510/xarr-rss-docs#19]
建议在数据源新增页面，增加下拉菜单可直接选择预置的网站列表，比如蜜柑计划、萌番组、动漫花园等等（可参考以前表格里的网站列表），并且标注是否需要代理。这样新用户大部分情况下只需要选择网站名称即可直接使用，无需手动寻找rss地址，降低使用难度。
对于PT用户也提供自定义Rss订阅地址的输入框，和现在一样。
优化项，优先级低。

**Comment by xiaoyi510** [comment]
已内置以下站点rss最新订阅


![Image](https://user-images.githubusercontent.com/20254874/181191115-c535117b-3016-4d24-852b-f389519b22fc.jpg)


蜜柑计划
萌番组
ACG.RIP
動漫花園
爱恋动漫
漫猫动漫
末日动漫
eztv
RARBG
