### ISSUE TITLE
通过判断集数来返回资源大小给sonarr

### ISSUE THREAD

**Issue by huoxin233** [xiaoyi510/xarr-rss-docs#32]
目前xarr-rss为了避免部分资源大小为0，直接写死资源大小为950.8MB
这造成一个问题就是 大合集 或者 个别片长较长的剧集合集 将无法通过sonarr自动下载的最低要求

以下面的神印王座为例：

![7 1$BIJ}MFXA3@3D9ZNOHPM](https://user-images.githubusercontent.com/23447157/195344848-620b8bb0-4f21-4b8f-8470-853bcbd8e32c.png)

质量为WEBDL-1080P，sonarr对WEBDL-1080P的最低限制值是"平均每分钟4MB"，而最高限制值是"平均每分钟130MB"，按神印王座的片长（20分钟）和集数（26集）计算，资源大小最低限制值为 4MBx20x26=2080MB，最高限制值为 130MB*20*26=67600MB

而写死的950.8MB远低于2080MB，若可通过xarr-rss获取到的最大和最小集数来计算这个资源里有多少集
（PS：集数=最大集-最小集+1），再通过 集数x950.8MB=最终返回的资源大小，就能更好的兼容合集下载
同样以上面的神印王座为例，合集最终的显示的大小应为 26*950.8MB=19016MB，在最低和最高限制值之间

**Comment by xiaoyi510** [comment]
已在 v2.0.0.4 处理
