### ISSUE TITLE
增加数据源开关功能和分组内数据源批量设置功能

### ISSUE THREAD

**Issue by dalamudx** [xiaoyi510/xarr-rss-docs#34]
数据源开关功能：
有些数据源设置完成后，访问不稳定，可以使用开关按钮来处理
分组内数据源批量设置功能：
例如已有4个数据源A、B、C、D
在添加分组的时候可以自由选择设置默认数据源A、B、C，等sonarr数据同步完成后，分组内剧集或番剧的数据源均为A、B、C
另外，如果后续想要调整分组内的多个剧集或番剧的数据源为B、C、D，希望有相应批量按钮来处理

**Comment by xiaoyi510** [comment]
模板功能已完成此功能
