### ISSUE TITLE
v2.0.0.8 无法对qb 4.4.5 中下载好的种子重命名

### ISSUE THREAD

**Issue by oglops** [xiaoyi510/xarr-rss-docs#41]
刚装上 v2.0.0.8 (编译时间:2022-11-23 11:43:57), 据说在 #31 中已修复，可是我还有有一样的问题，其他功能正常, qb连接正常

服务设置 里的qb 测试按钮 显示 请求成功

添加了一个分组，sonarr搜索正常， 能添加任务到qb

![image](https://user-images.githubusercontent.com/2757572/211174518-a60e5e8d-6c00-430d-af95-58f78f25dfcd.png)

但是qb没有重命名下载好的文件
![image](https://user-images.githubusercontent.com/2757572/211174556-7f3557cf-d56d-4269-b5b0-f23fcc413926.png)

导致下载完成后自动import失败
![image](https://user-images.githubusercontent.com/2757572/211174584-fd60e694-df0f-4867-b734-b595fb8bca57.png)

登入sonarr所在的podman container似乎可以重命名
```
root@pt:/# ll /data/torrent/sonarr/[SB*
-rw-rw-r--. 2 abc abc 304024059 Jan  7 23:23 '/data/torrent/sonarr/[SBSUB][CONAN][1064][1080P][HEVC_AAC][CHS_CHT_JP](693573D8).mkv'
-rw-rw-r--. 2 abc abc 270147723 Jan  7 23:08 '/data/torrent/sonarr/[SBSUB][CONAN][1065][1080P][HEVC_AAC][CHS_CHT_JP](4F505F85)x.mkv'
-rw-rw-r--. 2 abc abc 262220965 Jan  7 23:06 '/data/torrent/sonarr/[SBSUB][CONAN][1066][1080P][HEVC_AAC][CHS_CHT_JP](CA35A6FE).mkv'
-rw-rw-r--. 2 abc abc 303536807 Jan  7 22:50 '/data/torrent/sonarr/[SBSUB][CONAN][1068][1080P][HEVC_AAC][CHS_CHT_JP](D294F4E7).mkv'
```
在sonarr 网页ui也能重命名

**Comment by SanaeMio** [comment]
鼠标指向最后一张sonarr截图里的黄色下载图标，看下提示是什么

**Comment by xiaoyi510** [comment]
本身是不会重命名下载文件名的
只会修改任务名用于导入
我看截图任务名是已经修改成功了
具体还需要提供下 下载中的黄色图标提示
