### ISSUE TITLE
自动计算季错误，生成rss不包含季

### ISSUE THREAD

**Issue by moetayuko** [xiaoyi510/xarr-rss-docs#44]
## 问题
1. 自动匹配的季有些是错的，如(1, 4), (2, 3)的集、季数应该相同，但13正确，24错误
    > 他这个估计是原标题里有“第二季”然后就识别了第二季，然后32又是用的绝对集数，所以当成了S02E32
可能得增加判断第二季是否真的有32集，要是第二季没有32集就回落到绝对集数来计算
2. 即使匹配正确的条目，生成的rss也是错的。1234生成的rss都是绝对集数并且没有季

## 后台匹配结果

测试匹配完成,共匹配数量:4
 
1. 新标题:
[DMG&LoliHouse][伊甸星原] Edens Zero - S02E06 [Chinese][WEBDL-1080p][MKV]
源标题:
伊甸星原 [连载][DMG&LoliHouse][EDENS ZERO][1080p][31][MKV/WEBRip][2021年04月]
匹配集数:6 匹配季数:2

2. 新标题:
[DMG][伊甸星原] Edens Zero - S02E32 [Chinese][WEBDL-1080p][MP4]
源标题:
伊甸星原 第二季 [连载][DMG][EDENS ZERO 第2期][1080p][32][MP4/WEBRip][2023年04月]
匹配集数:32 匹配季数:2

4. 新标题:
[DMG&LoliHouse][伊甸星原] Edens Zero - S02E07 [Chinese][WEBDL-1080p][MKV]
源标题:
伊甸星原 [连载][DMG&LoliHouse][EDENS ZERO][1080p][32][MKV/WEBRip][2021年04月]
匹配集数:7 匹配季数:2

5. 新标题:
[DMG][伊甸星原] Edens Zero - S02E31 [Chinese][WEBDL-1080p][MP4]
源标题:
伊甸星原 第二季 [连载][DMG][EDENS ZERO][1080p][31][MP4/WEBRip][2023年04月]
匹配集数:31 匹配季数:2

## 生成RSS
```xml
<title>
<![CDATA[[DMG&LoliHouse][伊甸星原] Edens Zero - E31 [Chinese][WEBDL-1080p][MKV]]]>
</title>
<originalTitle>
<![CDATA[伊甸星原 [连载][DMG&LoliHouse][EDENS ZERO][1080p][31][MKV/WEBRip][2021年04月]]]>
</originalTitle>
```

```xml
<title>
<![CDATA[[DMG][伊甸星原] Edens Zero - E32 [Chinese][WEBDL-1080p][MP4]]]>
</title>
<originalTitle>
<![CDATA[伊甸星原 第二季 [连载][DMG][EDENS ZERO 第2期][1080p][32][MP4/WEBRip][2023年04月]]]>
</originalTitle>
```

```xml
<title>
<![CDATA[[DMG&LoliHouse][伊甸星原] Edens Zero - E32 [Chinese][WEBDL-1080p][MKV]]]>
</title>
<originalTitle>
<![CDATA[伊甸星原 [连载][DMG&LoliHouse][EDENS ZERO][1080p][32][MKV/WEBRip][2021年04月]]]>
</originalTitle>
```

```xml
<title>
<![CDATA[[DMG][伊甸星原] Edens Zero - E31 [Chinese][WEBDL-1080p][MP4]]]>
</title>
<originalTitle>
<![CDATA[伊甸星原 第二季 [连载][DMG][EDENS ZERO][1080p][31][MP4/WEBRip][2023年04月]]]>
</originalTitle>
```

**Comment by xiaoyi510** [comment]
已解决
