### ISSUE TITLE
添加专门番剧数据来源无法匹配，需要单独选择专门番剧数据进行识别

### ISSUE THREAD

**Issue by chendaren1** [xiaoyi510/xarr-rss-docs#45]
![@CPZU{7YE5JT1BCRSXVEY49](https://github.com/xiaoyi510/xarr-rss/assets/61540346/34fd1218-594b-47ab-a969-59a2b615b92e)

**Comment by xiaoyi510** [comment]
已解决
缓存5分钟问题
操作数据源之后会清理缓存
