### ISSUE TITLE
優先選取第一次的字幕組

### ISSUE THREAD

**Issue by xiNeRoar** [xiaoyi510/xarr-rss-docs#49]
下載新番之後 假如第一次系統自動下載了A字幕組 能不能設定成後續自動優先抓取A字幕組的發佈? 不用自己再手動設定

**Comment by xiaoyi510** [comment]
这种可以手动在分组媒体中设置关键字进行筛选

**Comment by xiNeRoar** [comment]
> 这种可以手动在分组媒体中设置关键字进行筛选

請問VIP有辦法可以自動嗎? 不用每次添加新番都要手動做一次
