### ISSUE TITLE
群暉CPU使用量拉滿

### ISSUE THREAD

**Issue by xiNeRoar** [xiaoyi510/xarr-rss-docs#50]
群暉機型: DS918+
DSM版本: DSM 7.2 一 64570 Update 3
安裝方式: DOCKER

只要本軟件開始運行, CPU至少會吃到50%, 還會經常上到99%導致CPU溫度過高
![image](https://github.com/xiaoyi510/xarr-rss/assets/66216186/b2eef157-b037-4400-bf45-cbef63878ec7)

**Comment by xiaoyi510** [comment]
可以限制他的cpu运行
初始运行会加载识别很多数据 正常的,,不过我没有你这么高过
![image](https://github.com/xiaoyi510/xarr-rss/assets/20254874/1a7c9290-9fa9-47f7-b6be-867ff4465e26)
