### ISSUE TITLE
群暉錯誤訊息

### ISSUE THREAD

**Issue by xiNeRoar** [xiaoyi510/xarr-rss-docs#51]
看群暉DOCKER裡不斷出現類似訊息 請問是正常的嗎?
<html>
<body>

2023/08/12 03:30:20 | stdout | 2023/08/12 03:30:20 [Error][同步数据源]保存数据源内容失败:sql: converting argument $6 type: unsupported type dbmodel.SourceItemEnclosure, a struct
-- | -- | --
2023/08/12 03:30:20 | stdout | [0.883ms] [rows:0] INSERT or ignore INTO `source_items` (`created_at`,`updated_at`,`source_id`,`hash`,`pub_date`,`enclosure`,`content`,`link`,`guid`,`title`,`parse_info`) VALUES ("2023-08-12 03:30:20.52","2023-08-12 03:30:20.52",7,"663557c99cd5bc1e82f5c58757350eb5","Sat, 12 Aug 2023 18:07:22 +0800","{  }","","https://greatposterwall.com/torrents.php?id=6475","c5aaa0dc69b07cc110ea8dfbca670443"," [心灵传输者] Jumper (2008) [Feature Film] - x264 / Blu-ray / 1080p / MKV / Encode / With Commentary / 50% off!","{\"analyze_title\":\"jumper   [feature film] -  /  /  /  / encode / with commentary / 50% off!\",\"video_encode\":[\"x264\"],\"media_type\":[\"MKV\"],\"min_episode\":2008,\"release_group\":\"心灵传输者\",\"language\":\"Unknown\"}") ON CONFLICT (`source_id`,`hash`) DO UPDATE SET `title`=`excluded`.`title`,`parse_info`=`excluded`.`parse_info`,`link`=`excluded`.`link`,`enclosure`=`excluded`.`enclosure` RETURNING `id`
2023/08/12 03:30:20 | stdout | 2023/08/12 03:30:20 /drone/src/app/service/source_item/source_item.go:142 sql: converting argument $6 type: unsupported type dbmodel.SourceItemEnclosure, a struct

</body>
</html>

**Comment by xiaoyi510** [comment]
加群问问 996973766

**Comment by xiaoyi510** [comment]
可能种子rss提供的数据有啥问题 导致 enclosure 没有什么东西
