### ISSUE TITLE
數據源找不到動畫

### ISSUE THREAD

**Issue by xiNeRoar** [xiaoyi510/xarr-rss-docs#52]
![image](https://github.com/xiaoyi510/xarr-rss/assets/66216186/0b6d7ae1-10c5-4e0a-9996-dc0053a48129)
在界面裡找不到指定的動畫 但在Mikan裡手動找是有的 請問這該怎麼解決?
![image](https://github.com/xiaoyi510/xarr-rss/assets/66216186/684e614d-b743-409e-a9ea-91ed995b1b60)
這是我數據源的設置
![image](https://github.com/xiaoyi510/xarr-rss/assets/66216186/92cb532d-8eeb-4022-8104-843348bd6c4e)
模板設置
![image](https://github.com/xiaoyi510/xarr-rss/assets/66216186/46772cf1-4ebe-4ceb-8564-9666f224f675)
![image](https://github.com/xiaoyi510/xarr-rss/assets/66216186/2e6ac275-53d0-4b2e-986b-c0d582d99644)
分組設置
![image](https://github.com/xiaoyi510/xarr-rss/assets/66216186/7ad3d442-bdf6-48f3-a9b9-b668876e0ac6)
搞不懂到底發生了什麼事....

**Comment by xiaoyi510** [comment]
可以加群询问,你用的代理模式可能不太美好

**Comment by xiaoyi510** [comment]
mikan 你就直接用rss功能都行

**Comment by xiNeRoar** [comment]
人在國外沒有qq也沒法創號..有其他方式可以問嗎
